# **Introducción** {#intro}

Las sociedades modernas, a diferenencia de las antepasadas, sufren un exceso de información y sin embargo requieren cada vez más de esta para convivir de manera eficiente. Este fenómeno, no sólo atañe a los individuos sino que cada vez y, con mayor frecuencia, se traslada a sus instituciones.

La gestión de la información a nivel de las entidades públicas ha adquirido un papel protagónico durante los últimos años. Muestra de ello, por ejemplo, loe s la dimensión de *Información y Comunicación* del Modelo Integrado de Planeación y Gestión - MIPG en donde se orienta a las entidades públicas a organizar y administrar de una manera eficiente la información bajo custodia institucional.

La guía que se presenta a continuación es un primer intento a nivel institucional por disponer de un documento que fije las directrices y dé las orientaciones requeridas a nivel de la Universidad para la consolidación, construcción y producción de estadísticas oficiciales. para ello, se propone que este ejercicio debe cumplir, como mínimo, los siguientes pasos metodológicos: *caracterización de usuarios, cumplimiento de requisitos de una estadística, caracterización de registros administrativos, procesamiento de datos, comunicación de resultados y cultura estadística*.
