# ***Conformar cifras agregadas***

La _segunda característica_ de las estadísticas está relacionada con la capacidad que estas tienen para representar la información de manera resumida o agregada. Las estadísticas no existen sin la disponibilidad de cifras descriptivas agregadas, producto de la actividad de contar o de medir, estas son su esencia. Las estadísticas se interesan por el descubrimiento de regularidades sociales, no es de su interés el estudio del comportamiento de rasgos individuales, aunque se valen de ellos para sus propósitos^[El ejercicio estadístico moderno, en el contexto de la construcción y consolidación de estadísticas nacionales e institucionales, se fundamenta en la otrora disciplina estadística de mediados del siglo pasado cuyo interés se centraba principalmente en el estudio de estos tipos de medidas y en especial aquellas requeridas y asociadas al contexto de los Estados. De hecho, en 1940 se definía a la disciplina estadística como “el cómputo o enumeración metódica de los hechos, de los individuos o de las cosas que pueden contarse o medirse y la coordinación de las cifras obtenidas”, en donde por coordinación se entendía “la aproximación, la comparación y el arreglo de las cifras, bajo la forma de cuadros y gráficos, para facilitar la utilización de ellas con fines prácticos y científicos” (@rodriguez, p. 16). Hoy, la disciplina estadística se ha acercado de manera importante a la línea matemática y científica en detrimento de la de mediados del siglo pasado, la cual podríamos catalogar como una estadística de naturaleza administrativa.]. 

Las medidas agregadas asociadas a las estadísticas son aproximaciones de tipo descriptivo que pueden ser de dos tipos: conteos o mediciones.

+ _Conteos: estadísticas derivadas de variables cualitativas_

El primer tipo de cifras derivadas del proceso de construcción de estadísticas lo conforman aquellas cuyo resultado es el producto de contar los individuos que conforman una población o muestra, o que al interior de estas comparten ciertos rasgos o atributos de interés. Por ejemplo, el total de estudiantes matriculados en un momento dado del tiempo y, de estos, cuántos son hombres, cuántas son mujeres, cuántos pertenecen a un estrato socioeconómico bajo, cuántos están ubicados en una determinada sede o facultad, etc., es el resultante de una actividad centrada en contar individuos y rasgos de estos al interior de una población la cual, en el caso de nuestro ejemplo, está conformada por los estudiantes matriculados en una universidad.

Las medidas estadísticas agregadas, producto de la actividad de contar, se construyen a partir de la disposición de variables nominales u ordinales. La construcción y disposición de estas variables ofrecen una gran posibilidad para contar y para construir series, a través de las cuales es posible observar los cambios y las tendencias que sufren las cifras a lo largo del tiempo. Esto último nos lleva a concluir que la construcción de estadísticas es más una actividad de cuantificación que de medición en sentido estricto; es decir, contar pero, sobre todo, contar bien, y para ello es suficiente con tener buenas nociones sobre los tipos de variables y las operaciones básicas de la aritmética^[Aunque el conteo es el ideal buscado, no siempre, por cuestiones técnicas o por exigencias institucionales, es posible alcanzarlo, en cuyo caso debemos acudir a las mediciones. Medir, desde luego, es tan importante en el contexto de la consolidación y construcción de estadísticas como contar.].

+ _Mediciones: estadísticas derivadas de variables cuantitativas_

El segundo tipo de cifras asociadas a la construcción de estadísticas lo conforman aquellas que miden ciertos parámetros de interés poblacional asociados al comportamiento de los individuos en una o más variables de interés. Mientras que el primer tipo de cifras asociadas a las estadísticas se centra en contar, este tipo de cifras se centra en medir, por ejemplo, las medidas de tendencia central como el promedio, la mediana o la moda; de posición no central como los cuartiles, deciles, quintiles o percentiles; de dispersión como la varianza, la desviación estándar o el rango; de apuntamiento como la kurtosis, y de simetría o asimetría.

La medición en el contexto de las estadísticas exige el uso y la disposición de variables cuantitativas al interior de las poblaciones que las soportan. A partir de este tipo de variables es posible construir cifras estadísticas agregadas que miden comportamientos globales de interés. Por ejemplo, en el contexto universitario, el promedio de edad de los estudiantes, su varianza, los cuartiles en las que estas se ubican, así como la asimetría observada hacen parte de las probables cifras estadísticas de naturaleza descriptiva que pueden medir estos parámetros de interés institucional.

+ _Transformación entre tipos de variables_

Las tipologías de las variables asociadas a una población o muestra, en el marco de la construcción de estadísticas, pueden ser transformadas en nuevas tipologías a través de un ejercicio de mutación de valores originales en nuevos valores. No obstante, no toda tipología de una variable puede ser transformada en una nueva tipología pues estas presentan ciertas reglas. La principal regla es la _imposibilidad de transformar variables cualitativas en cuantitativas_. La segunda regla es la _posibilidad de transformar variables cuantitativas en cualitativas, pero a lo sumo dentro de estas en variables ordinales_^[Existen más reglas de transformación de los tipos de variables, por ejemplo, la posibilidad de transformar  variables nominales en variables dicotómicas o _dummies_. El presente trabajo, por utilidad directa con el proceso de construcción de estadísticas, presenta únicamente dos reglas de transformación.]. Por ejemplo, desde una perspectiva estadística, la edad de un estudiante es una variable cuantitativa de razón, la cual puede ser transformada en una variable cualitativa ordinal a partir de la creación de clases o rangos de edad a la cual pertenecen las respectivas edades. En este sentido, un estudiante de pregrado con una edad de 17,5 años puede pertenecer a la clase de estudiantes con 18 años o menos, mientras que uno con 23 años puede pertenecer al grupo de estudiantes con 22 o más años y así sucesivamente, sin olvidar que cada una de las edades debe pertenecer a una única clase. 

La posibilidad de transformar variables cuantitativas en variables cualitativas favorece el proceso de construcción de estadísticas y debe ser usada si las circunstancias técnicas y funcionales lo permiten.

### ***Caracterizar y desagregar rasgos de interés de los individuos que conforman las poblaciones o muestras***

La _tercera característica_ de las estadísticas es la _capacidad de disponer y presentar información de manera desagregada_. En el apartado anterior se expuso que esta información se encuentra contenida en las variables disponibles en una población o muestra de origen. Las variables que conforman una población o muestra, para propósitos de construcción y disposición de estadísticas, pueden ser clasificadas a su vez según la posibilidad que estas tienen para representar la información de interés institucional desde diferentes perspectivas conocidas como desagregaciones. Las desagregaciones a través de las cuales se representa la información institucional, en el contexto de la universidad pública, son de tres tipos: temporales, geográficas/institucionales y temáticas.

+ _Desagregaciones temporales_

Una característica central de las estadísticas es la capacidad que tienen para representar la información desde una perspectiva temporal. En una universidad, por ejemplo, es tan importante conocer el número de matriculados en un momento dado del tiempo como su evolución histórica. La capacidad de las estadísticas para representar la información desde una perspectiva histórica implica la consolidación, el almacenamiento y la disposición de las poblaciones y muestras generadas a lo largo del tiempo. Los años, los semestres y, en una menor medida, los trimestres o meses son las variables comúnmente empleadas en el ámbito de la universidad colombiana para la provisión de estadísticas desde una perspectiva temporal^[Aunque en la teoría existe, y técnicamente hoy día es factible contar con información en tiempo real, para el caso de las estadísticas de una universidad pública es tolerable que estas estén medidas en periodos de tiempo que implican algunos rezagos en el acceso y la disposición de información institucional como son los semestres o los años.], y que conforman el subconjunto de desagregaciones temporales contenidas dentro de las poblaciones o muestras que las conforman.

+ _Desagregaciones geográficas e institucionales_

Los individuos que conforman una muestra o población asociada a la construcción de estadísticas generalmente se encuentran distribuidos espacialmente dentro de un territorio o ubicados jerárquicamente dentro de una estructura organizacional. La capacidad de las estadísticas para representar la información desde una perspectiva geográfica o institucional es una de las características esenciales que favorecen el hacer y la toma de decisiones en el contexto de lo público. Para una universidad como la Nacional es tan importante saber, por ejemplo, de qué municipios y departamentos del país proceden los estudiantes matriculados en un momento dado del tiempo como de qué países son los títulos obtenidos por sus docentes en sus máximos niveles de formación. Así mismo, a nivel institucional, es tan importante saber cuántos estudiantes están matriculados en una de sus sedes como el conocimiento sobre la distribución de estos por las respectivas facultades, institutos, escuelas y programas académicos de dichas sedes.

Las _desagregaciones geográficas nacionales e internacionales_ hacen un uso intensivo de información georreferenciada estandarizada a través de la cual es posible representar y comparar la información estadística institucional desde una perspectiva territorial. Las codificaciones estandarizadas de países, las distancias angulares de longitud y de latitud asociadas a un punto en un territorio particular, así como la disponibilidad de polígonos que representan áreas de interés nacional como los municipios o los departamentos hacen parte de los estándares requeridos para la disposición de estadísticas desde una perspectiva geográfica. En el módulo de cifras del sitio web de estadísticas de la Universidad Nacional de Colombia^[Ver UN - Cifras, en http://estadisticas.unal.edu.co/index.php?id=13] podrán ser exploradas, para el caso de poblaciones como los aspirantes y admitidos a pregrado y posgrado, los matriculados, los graduados y los docentes de carrera, representaciones geográficas a través de la disposición de mapas web interactivos con la distribución de estas poblaciones según el territorio en el que han nacido, proceden, residen o han alcanzado máximos niveles de formación, por ejemplo^[Esta información implica decisiones institucionales. Si, por ejemplo, se llegara a detectar que la población de aspirantes y admitidos a pregrado en la Universidad Nacional de Colombia se concentra solo en unos pocos municipios o departamentos del país, se podrían tomar medidas que permitan reiterar su carácter nacional.].

Además de la necesidad de disponer de información estadística desde un ámbito nacional e internacional, es de interés institucional que la información cuantitativa disponible tenga la capacidad de ser presentada desde una perspectiva interna –geografía institucional–. La forma como se organizan las universidades^[La Constitución Política de Colombia de 1991 reconoce la autonomía universitaria a todas las universidades del país, esto, a diferencia de otras entidades del Estado, les permite definir de manera libre la forma como se organizan y prestan el servicio público de educación superior.] difiere de manera importante, hecho que exige de las estadísticas el uso de normas internas que favorezcan la desagregación y presentación de la información cuantitativa desde una perspectiva organizacional. 

La organización y presentación de las estadísticas en una universidad debe tener la capacidad de reconocer, cuando así se requiera, la forma como estas se organizan. Por ejemplo, la Universidad Nacional de Colombia, según su Estatuto General^[Expedido mediante el Acuerdo 11 de 2005 del CSU, en http://www.legal.unal.edu.co/rlunal/home/doc.jsp?d_i=35137], se organiza académica y administrativamente en la actualidad en tres niveles: nivel nacional, nivel de sede y nivel de facultad, los cuales a su vez se subdividen en otros niveles. La Universidad tiene en la actualidad nueve sedes físicas ubicadas a lo largo del territorio nacional^[Bogotá, Medellín, Manizales, Palmira, Caribe, Orinoquia, Amazonia, Tumaco y La Paz.], hecho que exige el reconocimiento de sus particularidades y el fomento del uso y la disposición de la información cuantitativa que obedezca a la cultura de cada una de sus sedes. En esta universidad es tan importante contar con información cuantitativa a través de estadísticas a nivel nacional –el todo– como disponer de esta misma o nueva información en cada una de sus sedes. Por lo anterior, la apuesta actual de consolidación de un sistema estadístico a nivel institucional tiene entre sus retos ser capaz de representar la información de manera organizada tanto a nivel nacional como a través de cada una de sus sedes, y al interior de estas entre las facultades, escuelas y departamentos. A la fecha, además de la información oficial, estratégica y nacional contenida en el sitio web de estadísticas de esta universidad^[Ver UN en un vistazo, en http://estadisticas.unal.edu.co/], existen importantes ejercicios de consolidación de esta misma idea y de fomento de la cultura estadística en las sedes de esta institución, como lo evidencian los trabajos adelantados en este sentido en Bogotá^[Ver UN - La sede en cifras, en http://planeacion.bogota.unal.edu.co/cifras.html], Medellín^[http://planeacion.medellin.unal.edu.co/ opción ESTADISTICA] y Orinoquia^[Ver Boletín Estadístico de la Sede Orinoquia, en https://estadisticaun.github.io/BoletinOrinoquia/index.html], principalmente. 

+ _Desagregaciones temáticas_	

Las desagregaciones temáticas son características de los individuos que hacen parte de poblaciones o muestras las cuales trascienden el tiempo y la geografía y, al igual que estas, hacen parte constitutiva de las estadísticas. Por ejemplo, el sexo, el género, la edad, las condiciones socioeconómicas, la presencia de discapacidades, entre otras, hacen parte de los tipos de desagregaciones probables de ser tenidas en cuenta en las universidades para caracterizar las poblaciones humanas que hacen parte de sus comunidades.

Para la Universidad Nacional de Colombia, por ejemplo, son de interés desagregaciones temáticas de la estadística de aspirantes a pregrado: la presencia o ausencia de discapacidades, tipos de inscripción, nacionalidad, edad, estrato, sexo, puntajes en la prueba de admisión, tipo de inscripción, modalidades de inscripción, admitidos, pertenencia a programas de admisión especial, entre otras. Para el caso de las estadísticas de docentes, en esta institución las desagregaciones temáticas de interés son la edad, el sexo, la nacionalidad, el máximo nivel de formación, la dedicación, los años de servicio y la categoría docente. Cada población o muestra asociada a las estadísticas institucionales posee desagregaciones temáticas y es responsabilidad de cada universidad o entidad pública definir y caracterizar cuáles son de su interés.

### ***Representar el presente y el pasado***

Las entidades públicas, en especial aquellas encargadas de aportar al cumplimiento de derechos humanos y constitucionales como es el caso de la educación^[La educación fue reconocida como un derecho humano a partir de la inclusión del artículo 26 de la Declaración Universal de Derechos Humanos, la cual fue proclamada por la Asamblea General de las Naciones Unidas en París en el año 1948. Así mismo, en Colombia el derecho a la educación se encuentra consagrado en el artículo 67 de la Constitución Política el cual reza: “La educación es un derecho de la persona y un servicio público que tiene una función social; con ella se busca el acceso al conocimiento, a la ciencia, a la técnica, y a los demás bienes y valores de la cultura”.], además de disponer de la capacidad requerida para dar cumplimiento a estos deberes en los términos que la sociedad y los países lo demandan, deben proyectar y garantizar una gestión que trascienda los tiempos y los gobiernos. Las instituciones de educación en general, y las de educación superior en particular, por su naturaleza y por la labor que les ha encargado la sociedad, a diferencia de organizaciones privadas e incluso algunas entidades públicas, no pueden ni deben cambiar fácil y regularmente sus misiones, pues estas se encuentran atadas a un acuerdo social derivado de un derecho universal y constitucional como lo es la garantía de la educación y, con ella, el acceso de los miembros de la sociedad a los beneficios sociales, económicos y culturales que esta genera.

La *cuarta característica* de las estadísticas institucionales está relacionada con la capacidad que estas cifras deben tener para contar la historia que una entidad o institución pública ha vivido y, en ese sentido, rendir cuentas públicas a la sociedad sobre cómo estas han venido aportando al cumplimiento de las obligaciones y los derechos para las cuales fueron creadas. Las _series de tiempo_ son como técnicamente se conoce al conjunto de cifras estadísticas que reflejan la evolución histórica institucional. Estas, en el ámbito de lo público, son una muestra de las huellas que ha acumulado una institución a través de las cuales se da fe de una vida vivida, de posibles justificaciones, así como del horizonte hacia donde probablemente esta se dirige. La capacidad de las estadísticas para representar y contar hechos históricos institucionales a través de la consolidación y disposición de series de tiempo es uno de los aspectos definitorios de las estadísticas institucionales y constitutivos del ejercicio estadístico administrativo. No en vano, como lo mencionó @rodriguez en referencia a Schlozer, “la estadística es una historia estacionaria y la historia es la estadística en movimiento” (p. 19). A través de las series de tiempo se evidencia el grado de cumplimiento histórico de la misión encomendada a una institución por parte de una sociedad y, a partir de estas, es posible detectar la existencia de desviaciones y corregir el curso institucional cuando así se desee.

Desde una perspectiva formal e institucional, según la Norma Técnica de Calidad del Proceso Estadístico NTCPE 1000^[Expedida conjuntamente en el año 2017 por el DANE y el Icontec.], una serie histórica se define como una “sucesión de datos sobre una o más características que sean objeto de estudio, las cuales son consolidadas en intervalos de tiempo iguales (diario, semanal, semestral, anual, entre otros) y organizadas cronológicamente para permitir su análisis temporal teniendo en cuenta los cambios metodológicos que estas pueden presentar” (@DaneIcontec, pág. 14). Las características históricas que se miden desde las estadísticas generalmente hacen referencia a la evolución de las clases o los atributos asociados a las desagregaciones de las poblaciones o muestras bajo observación. Para el caso específico de la educación superior pública, los años y los semestres y, en menor medida los trimestres y los meses, son los intervalos de tiempo generalmente utilizados para la consolidación de las cifras históricas.

Contar con cifras históricas, además de ser uno de los requisitos centrales de las estadísticas, exige a nivel institucional la disposición y consolidación de la información desde una perspectiva temporal, hecho que trae consigo importantes retos para la gestión estadística institucional. En primer lugar, implica la disposición de desagregaciones temporales, lo cual se traduce en la consolidación y el almacenamiento histórico de la información contenida en las muestras o poblaciones asociadas a las estadísticas, cuya periodicidad dependerá de los intervalos de tiempo definidos para cada una de ellas. En segundo lugar, exige la definición de la forma como será almacenada la información poblacional o muestral histórica la cual, dados los avances tecnológicos actualmente existentes, puede ir desde archivos planos en _software_ de uso masivo como Excel, hasta la disposición de bases de datos sofisticadas como las bodegas de datos en donde se cuenta con la información institucional oportuna y de calidad para la gestión estadística institucional. Finalmente, la consolidación de series de tiempo a nivel institucional exige la existencia de un proceso metodológico claro y sostenible para su construcción, pues estas cifras, por su razón de ser, deben ser construidas de la misma manera a lo largo del tiempo.

Una muestra de que las series de tiempo son la memoria numérica escrita a través de la cual se da fe de una vida institucional vivida la constituyen, por ejemplo, los siguientes dos casos de aplicación de estas en el contexto de las estadísticas institucionales de la Universidad Nacional de Colombia los cuales, entre múltiples muestras de series de tiempo contenidas en el sitio web oficial de las cifras institucionales^[Ver UN en un vistazo, en http://estadisticas.unal.edu.co/], evidencian la importancia de la construcción, conservación y disposición de este tipo de medidas en el contexto de las entidades públicas en Colombia y, en específico, en las universidades tanto del orden nacional como del regional..... 
