# ***Tener la capacidad de reconocer y representar el comportamiento de grupos poblacionales minoritarios*** 

Según la Constitución Política de Colombia de 1991, en Colombia:

> Todas las personas nacen libres e iguales ante la ley, recibirán la misma protección y trato de las autoridades y gozarán de los mismos derechos, libertades y oportunidades sin ninguna discriminación por razones de sexo, raza, origen nacional o familiar, lengua, religión, opinión política o filosófica. El Estado promoverá las condiciones para que la igualdad sea real y efectiva y adoptará medidas en favor de grupos discriminados o marginados. El Estado protegerá especialmente a aquellas personas que, por su condición económica, física o mental, se encuentren en circunstancia de debilidad manifiesta y sancionará los abusos o maltratos que contra ellas se cometan.^[Artículo 13 de la Constitución Política de Colombia de 1991.]
Así mismo, nuestra Constitución indica que: “El Estado reconoce y protege la diversidad étnica y cultural de la Nación colombiana”^[Artículo 6 de la Constitución Política de Colombia de 1991.].

Con la expedición de la Constitución Política de 1991, los grupos poblacionales minoritarios, las poblaciones históricamente marginadas, los miembros de la sociedad con limitaciones físicas o psicológicas, las poblaciones que han vivido en condiciones de desigualdad e inequidad, así como los que enriquecen la diversidad étnica y cultural de nuestro país y nos dan identidad como nación adquieren un lugar preponderante, primero en su reconocimiento y, segundo, en el derecho a participar y acceder a los bienes de la sociedad, entre ellos la educación.

La _quinta característica_ de las estadísticas está relacionada con la capacidad que este tipo de cifras tienen, en el ámbito de lo público, para representar a las poblaciones que hacen parte de la sociedad sin discriminaciones por razones de sexo, raza, origen, religión, opinión política, filosofía, etc. 

En la actualidad, las cifras de estadísticas públicas de nuestro país por omisión, costos, complejidad en la recolección, ausencia de conceptos, normas, o por otros motivos, como lo reconoce el Plan Estadístico Nacional 2017-2022, evidencian una importante ausencia de información con un enfoque diferencial, de forma tal “que se puedan analizar de manera conjunta las situaciones en las que convergen distintos tipos de discriminación: etnia, género, orientación sexual, entre otros” (@Dane2017, pág. 12). Para enmendar esta situación, el Plan Estadístico Nacional apuesta, en su quinta línea estratégica, por la “promoción de la inclusión del enfoque diferencial e interseccional en la producción y difusión de las estadísticas del Sistema Estadístico Nacional SEN” (pág. 28); así mismo, conmina a que, a más tardar en el año 2022, las estadísticas oficiales del país que sean objeto de este enfoque lo incluyan (pág. 29). 
	
La necesidad de la disposición de estadísticas incluyentes o con un enfoque diferencial en el contexto de las entidades públicas implica abordar y superar ciertos retos, algunos de naturaleza política y otros de técnica estadística, entre los que se destacan: en primer lugar, pocas entidades y universidades reconocen hoy efectivamente la responsabilidad, el valor y la riqueza que tiene la existencia de poblaciones diversas al interior de las instituciones, hecho que ha traído como consecuencia la imposibilidad de identificar cuantitativamente a sus miembros y, por ende, visibilizarlos a través de la disposición de estadísticas institucionales. Miembros de comunidades en situación de discapacidad, paridad de género, presencia de indígenas, afros, raizales, palenqueros, gitanos o población Rom, víctimas del conflicto interno armado; población ubicada en municipios con baja densidad demográfica, alejados de las urbes o con altos niveles de pobreza, etc., hacen parte de las múltiples caras de los integrantes que conforman la nación colombiana los cuales, en un país que busca reducir los niveles de olvido e inequidad al que han sido históricamente expuestos, merecen un lugar privilegiado al interior del Estado, en las universidades públicas y, desde luego, en sus cifras institucionales.

En segundo lugar, las estadísticas se caracterizan por ser altamente discriminatorias si no se reconoce el valor que tienen para una sociedad ciertas cifras cuyo tamaño resulta insignificante o atípico, desde una perspectiva estadística, pero inmensamente significativo desde una perspectiva social. Representar gráficamente cifras pequeñas en presencia de grandes datos^[En la figura \@ref(fig:fig31) se ilustra con un ejemplo cómo la tecnología que existe hoy nos permite avanzar en la representación gráfica de estadísticas con perspectivas diferenciales e incluyentes.] puede llevar a desconocer la presencia de dichos datos y a eliminarlos dada su atipicidad. En ciertas ocasiones, como en el caso de las estadísticas inclusivas o con un enfoque diferencial, hay que ser sumamente cuidadosos con este aspecto. Por ejemplo, la presencia de estudiantes matriculados pertenecientes a comunidades afrodescendientes, en comparación con el total de estudiantes, en una universidad como la Universidad Nacional de Colombia o en el sector de la educación en general, podría no ser tenida en cuenta y el impacto sobre la cifra global de matriculados ser mínimo. 

La totalidad de estadísticas asociadas a las poblaciones estudiantiles^[Este estamento, por su importancia, es el que actualmente ofrece cifras estratégicas con un enfoque diferencial. A futuro se espera consolidar esta información en todos los subtipos de poblaciones estudiantiles y avanzar en la misma dirección en los estamentos de docentes y administrativos de carrera.] en la Universidad Nacional de Colombia, por ejemplo, como puede ser corroborado y explorado en el sitio web institucional en donde se aloja la información estratégica oficial, incluye desagregaciones que reconocen y visibilizan la existencia de un número importante de integrantes pertenecientes a poblaciones minoritarias o excluidas como, por ejemplo, los integrantes de poblaciones indígenas, afros, raizales, víctimas del conflicto interno armado en Colombia, mejores bachilleres del país, mejores bachilleres provenientes de municipios pobres, en situación de discapacidad y estudiantes ubicados en las fronteras del país los cuales aspiran, son admitidos y se matriculan en la mayoría de los casos de manera particular o específica en esta institución a través de programas especiales, ejemplos de movilidad social en este país, como el PAES y el Programa Especial de Admisión y Movilidad Académica (Peama)^[El Peama tiene como propósito proyectar la institución en el territorio nacional y, en específico, en departamentos y municipios con baja o nula cobertura de programas de educación superior, de difícil acceso o con problemas de orden público. Su foco de acción se concentra de manera especial en aspirantes provenientes de los departamentos de San Andrés, Providencia y Santa Catalina, Amazonas, Guainía, Guaviare, Putumayo, Vaupés, Arauca, Casanare, Vichada y algunos municipios o localidades de los departamentos de Caquetá, Chocó, Nariño, Boyacá, Norte de Santander, Caldas y Bogotá.].

### ***Poder ser representadas de manera tabular y gráfica***